# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    # You can also specify other tool versions:
    # nodejs: "19"
    # rust: "1.64"
    # golang: "1.19"

# Build documentation in the docs/ directory with Sphinx
# Sphinx config
sphinx:
   configuration: docs/conf.py
   fail_on_warning: true
   
# Install our python package before building the docs
python:
  install:
    - method: pip
    - requirements: docs/requirements.txt

# Build all formats
  formats: all
  
